version: '2'

services:
  faucet:
    image: faucet:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    environment:
      - STATIC_ROOT=/faucet/static/
      - UPVEST_OAUTH_CLIENT_ID
      - UPVEST_OAUTH_CLIENT_SECRET
      - UPVEST_USERNAME
      - UPVEST_PASSWORD
      - WHITELISTED_IPS
      - WHITELISTED_HEADERS
      - ALLOWED_HOSTS
      - DEBUG
      - USE_STATSD
      - STATSD_HOST
      - STATSD_PORT
