version: '3'

services:

  # data stores
  db:
    image: postgres
    environment:
      - POSTGRES_USER=faucet
      - POSTGRES_PASSWORD=faucet
      - POSTGRES_DB=faucet
    ports:
      - 6041:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  broker:
    image: rabbitmq:latest
    ports:
      - 60542:5672
    volumes:
      - rabbitdata:/var/lib/rabbitmq

volumes:
  pgdata:
  rabbitdata:
